worker_processes 1;

events {
    worker_connections 1024;
}

http {
    # include mime.types;
    default_type application/octet-stream;

    sendfile on;

    upstream backend {
        # least_conn; //áàëàíñèðîâêà 
        # ip_hash; //äðóãàÿ áàëàíñèðîâêà
        server localhost:5001;
        server localhost:5002;
    }

    # 8080 ïîðò - òî÷êà âõîäà äëÿ ïîëüçîâàòåëåé
    server {
        listen 8080;
        server_name localhost;

        location / {
            proxy_pass http://backend;
        }
    }
    # http-ñåðâåð íà 8082 ïîðòó âñåãäà âîçâðàùàåò ñòðîêó "8082"
    server {
        listen 8082;

        location / {
            return 200 '8082';
            add_header Content-Type text/plain;
        }
    }
}